### ISSUE TITLE
Dockerize

### ISSUE THREAD

**Issue by Wilkuu-2** [Wilkuu-2/website_warp#2]
To make deployment easy, the project should migrate to a docker container.

**Comment by harshit82** [comment]
Hey @Wilkuu-2, I am new to Docker and am looking for projects to contribute to and learn.
Can I work on this?

**Comment by Wilkuu-2** [comment]
Hello, @harshit82, I do not think this is a good project for you to work on. 
First off, this is a personal project of mine, so I do not accept help. 
Second, rust containers are slow to build, making them irritating when having to rebuild them. Third, there is already a branch on the way that solves this issue: [update/docker](https://github.com/Wilkuu-2/website_warp/tree/update/docker).

My suggestion would be either following the official [docker tutorial](https://www.docker.com/101-tutorial/) or trying to put one of your existing projects into a docker container, preferably written in a language that does not have to be compiled, (Python, PHP, etc.).

Anyway,
Best of luck!

**Comment by harshit82** [comment]
Thanks for your insight.
